name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: []
assignees:
  - devops-rob
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: gh_handle
    attributes:
      label: Github handle
      description: What is your Github handle?
      placeholder: ex. devops-rob
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: Please describe the issue you are facing?
      description: Also tell us, what did you expect to happen and what actually happened?
      placeholder: Tell us what you see!
      value: "Terra stopped curling"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Please detail the steps to reproduce the issue?
      description: Please provide as much detail as possible to assist with debugging?
      placeholder: Tell us what you see!
      value: |
        step 1: do this
        step 2: do that
        step 3: etc
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: TerraCurl provider version
      description: What version of TerraCurl are you running?
      options:
        - 2.0.0
        - 1.2.2 (Default)
        - 1.2.1
        - 1.2.0
        - 1.1.0
        - 1.0.2
        - 1.0.1
        - 1.0.0
        - 0.1.1
        - 0.1.0
        - version not listed (please include the version in the description)
      default: 1
    validations:
      required: true
  - type: dropdown
    id: tf_version
    attributes:
      label: What version of Terraform are you using?
      multiple: false
      options:
        - 1.3.*
        - 1.4.*
        - 1.5.*
        - 1.6.*
        - 1.7.*
        - 1.8.*
        - 1.9.*
        - 1.10.*
        - 1.11.*
  - type: dropdown
    id: os_arch
    attributes:
      label: What Operating system architecture are you running?
      multiple: false
      options:
        - darwin_amd64
        - darwin_arm64
        - linux_amd64
        - linux_arm64
        - windows_386
        - windows_amd64
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
